Mobile menu creation
massaillon/setup-and-mobile-version-skeleton pull request #13
Opened 2022-05-12 14:50 UTC by massaillon

We have created the mobile menu as per the below requirements:

    - When the user clicks (or taps) the hamburger button, the mobile menu appears.
    - When the user clicks (or taps) the close (X) button, the mobile menu disappears.
    - When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
    - When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

2022-05-12 15:27 UTC, RolandM99 requested changes
Hi @massaillon , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-12 15:27 UTC, RolandM99 commented on index.html
> +        </div>
- [ ] The hamburger menu should have the same color as on the original design. Please, kindly make sure that your menu bar(hamburger) has the same color as the color of your website logo.
![image](https://user-images.githubusercontent.com/71874425/168106999-c0b32756-94be-4ecc-813f-72c42322e53c.png)

2022-05-12 15:27 UTC, RolandM99 commented on style.css
> +  opacity: 95%;
- [ ] Good job so far by implementing the mobile menu, now it's functional but, to make it accepted by the standard and also presentable you have to fit exactly the design provide by the original design from Figma.

| Your design | Figma design |
| --------------| --------------- |
| ![image](https://user-images.githubusercontent.com/71874425/168111476-88b79581-6ced-4b2c-ab00-56be37dc06fd.png)| ![image](https://user-images.githubusercontent.com/71874425/168109251-2389195b-01eb-41a7-8ae5-833ceccf4af8.png)|

- Kindly, make sure that you fit exactly this template provided by the Figma design. background-color, font, size, and color should be the same. Let's rock, fix this issue 😃

2022-05-13 17:24 UTC, roshan-bajgain requested changes
Hi @massaillon, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-13 17:24 UTC, roshan-bajgain commented on index copy.html
> +            </li>
- [ ] Kindly adjust the spacing as there is more spacing from the top.
- [ ] If you see the background blur then It is not like the Figma design so Kindly make the less blur to stick with Figma design.
### Figma design
![spac](https://user-images.githubusercontent.com/81727988/168334705-0d3979f8-b6c1-4a02-9da5-2820c2c82892.png)

### Your design

![adjust](https://user-images.githubusercontent.com/81727988/168334877-b84a05be-7680-4cbb-8672-eeb0ca5bb2c3.png)

2022-05-13 17:24 UTC, roshan-bajgain commented on index copy.html
> +        </div>
- [ ] If you see the Figma design then the `X` buttons are not similar to the design kindly make the design similar with the Figma 
### your design
![his](https://user-images.githubusercontent.com/81727988/168335589-330c3147-a0f7-46e7-ae58-119a9a6bea5c.png)
### Figma design

![figma](https://user-images.githubusercontent.com/81727988/168335756-63144970-d7a4-443d-8c54-ce130309bbfe.png)

2022-05-16 13:00 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @massaillon👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
- [ ] This is a pair-programming project, every member of your group needs to contribute to this project. I am requesting some changes Please make sure to implement the changes with your group. We will see the commit history.
- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-16 13:00 UTC, thecodechaser commented on index.html
> +                <a  href="#main-home" class="nav-link">Portfolio</a>
- [ ] You did a good job on the functionalities but there is a little issue, When I click on any of the mobile-menu options, It takes to contact form. Please fix this issue and make sure when users click on the mobile-menu options it takes to the correct part of the webpage.

2022-05-16 13:00 UTC, thecodechaser commented on index.html
> +        <ul class="nav-menu hide">
- [ ] Please apply the blur effect to the mobile menu background and make sure it matches with [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) design.
  - For blur effect you can use this CSS `backdrop-filter: blur(5px);` change px according to your design.

### Your design

![image](https://user-images.githubusercontent.com/83803414/168597622-9b238c2d-faca-4275-ab7d-26a13b0d7b08.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/168597605-a640c394-fbb5-48ba-9501-6b0bb9099530.png)

2022-05-16 20:51 UTC, gemmen29 approved these changes
Hi @massaillon, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-16 23:47 UTC, merged